import React, { createContext, useContext, useState, useEffect } from "react";
import { useTranslation } from "react-i18next";
import { getHospitalImage, getCosmeticAdImage, getMedicalAdImage } from "./App";

const DataContext = createContext();

export const DataProvider = ({ children }) => {
  const { t, i18n } = useTranslation();
  const [data, setData] = useState({
    favoritesData: [],
    facilityInfo: {},
    gymReviews: [],
    gymData: {},
    trainerInfo: {},
    trainerReviews: [],
    trainerData: {},
    communityData: {},
  });

  useEffect(() => {
    setData({
      favoritesData: [
        {
          id: 1,
          type: "medical",
          title: "서울 연세 내과",
          image: getMedicalAdImage("all", 1),
          subtitle: "심장내과 전문 병원",
          rating: 4.8,
          reviewCount: 124,
          description:
            "혈액검사, CT, 초음파, 암 표지자 검사까지 한번에! 건강한 삶을 위한 첫걸음, 지금 예약하세요.",
          tags: ["내과", "검진", "할인 이벤트"],
          price: "검진 비용 문의",
          location: "서울시 강남구",
          distance: "2.3km",
          isEvent: true,
          eventPeriod: "3.25 - 4.30",
          eventContent: "종합검진 패키지 특별 할인",
          originalPrice: "150,000원",
          discountPrice: "120,000원",
          discountRate: "20%",
          // 추가된 카테고리 정보
          mainCategory: "chest", // 가슴/심장 문제
          subCategory: "chest-pain", // 가슴이 아파요
          // 추가된 전문 과목 정보
          specialty: "cardiology", // 심장내과
          facilityType: "clinic", // 의원
        },
        {
          id: 2,
          type: "medical",
          title: "김연아 정형외과",
          image: getHospitalImage("all", 3),
          subtitle: "관절 전문",
          rating: 4.9,
          reviewCount: 213,
          description: "관절 통증이나 스포츠 손상에 특화된 클리닉. 예약 필수.",
          tags: ["정형외과", "관절", "스포츠"],
          price: "진료비 5,000원~",
          location: "서울시 서초구",
          distance: "3.7km",
          isEvent: false,
          // 추가된 카테고리 정보
          mainCategory: "joint", // 관절/근육 통증
          subCategory: "joint-knee", // 무릎이 아파요
          // 추가된 전문 과목 정보
          specialty: "orthopedics", // 정형외과
          facilityType: "clinic", // 의원
        },
        {
          id: 3,
          type: "cosmetic",
          title: "뷰티 클리닉 센터",
          image: getCosmeticAdImage("all", 1),
          subtitle: "피부 관리 전문",
          rating: 4.6,
          reviewCount: 86,
          description:
            "개인 맞춤형 피부 관리 프로그램. 첫 방문 고객 상담료 무료.",
          tags: ["피부 관리", "레이저", "할인 이벤트"],
          price: "시술 60,000원~",
          location: "서울시 마포구",
          distance: "1.5km",
          isEvent: true,
          eventPeriod: "3.15 - 4.15",
          eventContent: "첫 방문 고객 상담료 무료",
          originalPrice: "60,000원",
          discountPrice: "무료 (상담)",
          discountRate: "100%",
          mainCategory: "skin",
          subCategory: "skin-basic",
          // 새로 추가된 정보
          specialty: "dermatology",
          facilityType: "clinic",
        },
        {
          id: 4,
          type: "cosmetic",
          title: "라인 성형외과",
          image: getHospitalImage("all", 4),
          subtitle: "안면윤곽 전문",
          rating: 4.7,
          reviewCount: 156,
          description: "개인별 맞춤 안면윤곽 디자인. 상담 예약 후 방문 필수.",
          tags: ["성형외과", "안면윤곽"],
          price: "상담 무료",
          location: "서울시 강남구",
          distance: "0.8km",
          isEvent: false,
          // 추가된 카테고리 정보
          mainCategory: "face", // 얼굴 성형
          subCategory: "face-contour", // 얼굴 윤곽
          // 새로 추가된 정보
          specialty: "plastic", // 성형외과
          facilityType: "clinic", // 의원
        },
        {
          id: 5,
          type: "medical",
          title: "굿모닝 치과",
          image: getHospitalImage("all", 5),
          subtitle: "임플란트 전문",
          rating: 4.5,
          reviewCount: 178,
          description:
            "첨단 디지털 장비를 활용한 무통 임플란트. 3월 한정 스케일링 할인.",
          tags: ["치과", "임플란트", "스케일링"],
          price: "상담 무료",
          location: "서울시 송파구",
          distance: "4.2km",
          isEvent: true,
          eventPeriod: "3.01 - 3.31",
          eventContent: "스케일링 + 검진 패키지",
          originalPrice: "80,000원",
          discountPrice: "49,000원",
          discountRate: "38%",
          // 추가된 카테고리 정보
          mainCategory: "dental", // 치아 관련 (추가 카테고리로 가정)
          subCategory: "dental-implant", // 임플란트 (가정)
          // 새로 추가된 정보
          specialty: "dentistry", // 치과
          facilityType: "dental", // 치과
        },
        {
          id: 6,
          type: "medical",
          title: "힐링 한의원",
          image: getMedicalAdImage("all", 2),
          subtitle: "체질 분석 전문",
          rating: 4.7,
          reviewCount: 142,
          description:
            "개인 체질에 맞는 맞춤형 한방 치료와 침술. 첫 방문 체질 분석 검사 50% 할인 중.",
          tags: ["한의원", "침술", "체질 분석"],
          price: "진료비 15,000원~",
          location: "서울시 용산구",
          distance: "3.1km",
          isEvent: true,
          eventPeriod: "4.01 - 4.30",
          eventContent: "체질 분석 + 침술 패키지",
          originalPrice: "70,000원",
          discountPrice: "35,000원",
          discountRate: "50%",
          // 추가된 카테고리 정보
          mainCategory: "sleep", // 수면/피로
          subCategory: "sleep-energy", // 기운이 없어요
          // 새로 추가된 정보
          specialty: "oriental", // 한의원
          facilityType: "oriental", // 한의원
        },
        {
          id: 7,
          type: "cosmetic",
          title: "글로우 피부과",
          image: getCosmeticAdImage("all", 2),
          subtitle: "여드름 흉터 개선 전문",
          rating: 4.8,
          reviewCount: 203,
          description:
            "맞춤형 피부 리모델링으로 여드름 흉터 개선. 봄맞이 특별 프로모션 진행 중.",
          tags: ["피부과", "여드름", "흉터"],
          price: "상담 무료",
          location: "서울시 강동구",
          distance: "5.5km",
          isEvent: true,
          eventPeriod: "4.01 - 5.15",
          eventContent: "피부 리모델링 시술 할인",
          originalPrice: "250,000원",
          discountPrice: "180,000원",
          discountRate: "28%",
          // 추가된 카테고리 정보
          mainCategory: "scar", // 흉터/점 제거
          subCategory: "scar-acne", // 여드름 흉터
        },
        {
          id: 8,
          type: "medical",
          title: "맑은눈 안과",
          image: getHospitalImage("all", 2),
          subtitle: "노안/백내장 전문",
          rating: 4.9,
          reviewCount: 189,
          description:
            "최신 장비로 정밀한 시력 검사와 노안 교정. 60세 이상 시력 검사 무료 이벤트.",
          tags: ["안과", "노안", "백내장"],
          price: "진료비 10,000원~",
          location: "서울시 종로구",
          distance: "4.7km",
          isEvent: false,
          // 추가된 카테고리 정보
          mainCategory: "eye", // 눈 문제
          subCategory: "eye-vision", // 시력이 안 좋아졌어요
          // 새로 추가된 정보
          specialty: "ophthalmology", // 안과
          facilityType: "clinic", // 의원
        },
        {
          id: 9,
          type: "cosmetic",
          title: "에스테틱 클리닉",
          image: getCosmeticAdImage("all", 3),
          subtitle: "비수술 리프팅 전문",
          rating: 4.6,
          reviewCount: 167,
          description:
            "최신 고주파 장비를 이용한 비수술 리프팅. 5월까지 특별 할인 프로모션.",
          tags: ["리프팅", "안티에이징", "할인 이벤트"],
          price: "시술 150,000원~",
          location: "서울시 서초구",
          distance: "2.9km",
          isEvent: true,
          eventPeriod: "4.15 - 5.31",
          eventContent: "울쎄라 리프팅 특가",
          originalPrice: "450,000원",
          discountPrice: "320,000원",
          discountRate: "29%",
          // 추가된 카테고리 정보
          mainCategory: "antiaging", // 노화 방지
          subCategory: "antiaging-lifting", // 리프팅
        },
        {
          id: 10,
          type: "medical",
          title: "튼튼 소아과",
          image: getMedicalAdImage("all", 3),
          subtitle: "영유아 전문 의원",
          rating: 4.8,
          reviewCount: 231,
          description:
            "아이들을 위한 친환경 진료 환경과 최신 의료 시스템. 4월 예방접종 할인 이벤트.",
          tags: ["소아과", "예방접종", "소아 알레르기"],
          price: "진료비 8,000원~",
          location: "서울시a 노원구",
          distance: "6.3km",
          isEvent: true,
          eventPeriod: "4.01 - 4.30",
          eventContent: "영유아 건강검진 패키지",
          originalPrice: "120,000원",
          discountPrice: "89,000원",
          discountRate: "26%",
          // 추가된 카테고리 정보
          mainCategory: "allergy", // 알레르기
          subCategory: "allergy-respiratory", // 알레르기성 비염이 있어요
          // 새로 추가된 정보
          specialty: "pediatrics", // 소아과
          facilityType: "clinic", // 의원
        },
        // 머리두통 - 두통이 있어요 (5개)
        {
          id: 11,
          type: "medical",
          title: "두통케어 클리닉",
          image: getMedicalAdImage("all", 2),
          subtitle: "두통 전문 치료센터",
          rating: 4.7,
          reviewCount: 152,
          description:
            "편두통, 긴장성 두통, 군발성 두통 등 모든 유형의 두통 전문 진료와 맞춤형 치료.",
          tags: ["신경과", "두통", "편두통"],
          price: "진료비 20,000원~",
          location: "서울시 강남구",
          distance: "2.5km",
          isEvent: true,
          eventPeriod: "4.1 - 4.30",
          eventContent: "두통 종합검진 패키지 할인",
          originalPrice: "150,000원",
          discountPrice: "120,000원",
          discountRate: "20%",
          mainCategory: "head",
          subCategory: "head-pain",
          // 추가된 전문 과목 정보
          specialty: "neurology", // 신경과
          facilityType: "clinic", // 의원
        },
        {
          id: 12,
          type: "medical",
          title: "서울 두통 클리닉",
          image: getMedicalAdImage("all", 3),
          subtitle: "만성 두통 전문",
          rating: 4.9,
          reviewCount: 187,
          description:
            "만성 두통, 원인불명 두통 전문 치료. 최신 진단 장비와 다양한 치료법 보유.",
          tags: ["두통", "만성통증", "신경과"],
          price: "진료비 25,000원~",
          location: "서울시 서초구",
          distance: "3.2km",
          isEvent: false,
          mainCategory: "head",
          subCategory: "head-pain",
          // 추가된 전문 과목 정보
          specialty: "neurology", // 신경과
          facilityType: "clinic", // 의원
        },
        {
          id: 13,
          type: "medical",
          title: "뉴로 헤드 센터",
          image: getMedicalAdImage("all", 4),
          subtitle: "두통 및 신경통 전문",
          rating: 4.8,
          reviewCount: 165,
          description:
            "두통, 안면신경통, 삼차신경통 등 두경부 통증 전문 진료. 정확한 원인 진단과 치료.",
          tags: ["신경과", "두통", "신경통"],
          price: "진료비 22,000원~",
          location: "서울시 강남구",
          distance: "2.8km",
          isEvent: true,
          eventPeriod: "4.15 - 5.15",
          eventContent: "두통 집중 치료 프로그램",
          originalPrice: "300,000원",
          discountPrice: "240,000원",
          discountRate: "20%",
          mainCategory: "head",
          subCategory: "head-pain",
          // 추가된 전문 과목 정보
          specialty: "neurology", // 신경과
          facilityType: "clinic", // 의원
        },
        {
          id: 14,
          type: "medical",
          title: "편두통 스페셜 클리닉",
          image: getMedicalAdImage("all", 5),
          subtitle: "편두통 특화 진료",
          rating: 4.6,
          reviewCount: 143,
          description:
            "편두통, 군발성 두통 등 심한 두통에 특화된 진료. 예방 및 급성기 치료 모두 가능.",
          tags: ["편두통", "군발두통", "통증의학과"],
          price: "진료비 18,000원~",
          location: "서울시 송파구",
          distance: "4.5km",
          isEvent: false,
          mainCategory: "head",
          subCategory: "head-pain",
          // 추가된 전문 과목 정보
          specialty: "pain", // 통증의학과
          facilityType: "clinic", // 의원
        },
        {
          id: 15,
          type: "medical",
          title: "통증 없는 클리닉",
          image: getMedicalAdImage("all", 1),
          subtitle: "두통 및 만성통증 전문",
          rating: 4.7,
          reviewCount: 176,
          description:
            "두통, 경추성 두통, 긴장성 두통 등 모든 유형의 두통 진료. 비약물적 치료도 제공.",
          tags: ["통증의학과", "두통", "만성통증"],
          price: "진료비 20,000원~",
          location: "서울시 강남구",
          distance: "2.1km",
          isEvent: true,
          eventPeriod: "4.1 - 5.31",
          eventContent: "두통 치료 첫 방문 할인",
          originalPrice: "80,000원",
          discountPrice: "60,000원",
          discountRate: "25%",
          mainCategory: "head",
          subCategory: "head-pain",
          // 추가된 전문 과목 정보
          specialty: "pain", // 통증의학과
          facilityType: "clinic", // 의원
        },
        {
          id: 16,
          type: "medical",
          title: "굿슬립 수면의학센터",
          image: getMedicalAdImage("all", 4),
          subtitle: "수면장애 전문",
          rating: 4.6,
          reviewCount: 118,
          description:
            "불면증, 수면무호흡증, 코골이, 하지불안증후군 등 수면장애 전문 진료 및 치료.",
          tags: ["신경과", "수면장애", "불면증"],
          price: "진료비 20,000원~",
          location: "서울시 서초구",
          distance: "3.4km",
          isEvent: false,
          mainCategory: "sleep",
          subCategory: "sleep-insomnia",
          // 추가된 전문 과목 정보
          specialty: "neurology", // 신경과
          facilityType: "clinic", // 의원
        },
        {
          id: 17,
          type: "medical",
          title: "비전케어 안과",
          image: getMedicalAdImage("all", 5),
          subtitle: "시력교정 전문",
          rating: 4.9,
          reviewCount: 246,
          description:
            "시력저하, 백내장, 녹내장, 안구건조증 등 눈 질환 전문 진료. 최신 검사 장비 보유.",
          tags: ["안과", "시력검사", "안구건조증"],
          price: "진료비 15,000원~",
          location: "서울시 강남구",
          distance: "2.1km",
          isEvent: true,
          eventPeriod: "4.15 - 5.15",
          eventContent: "노안 검사 패키지 할인",
          originalPrice: "80,000원",
          discountPrice: "60,000원",
          discountRate: "25%",
          mainCategory: "eye",
          subCategory: "eye-vision",
          // 추가된 전문 과목 정보
          specialty: "ophthalmology", // 안과
          facilityType: "clinic", // 의원
        },
        {
          id: 18,
          type: "medical",
          title: "청각케어 이비인후과",
          image: getMedicalAdImage("all", 1),
          subtitle: "청력/귀 질환 전문",
          rating: 4.7,
          reviewCount: 132,
          description:
            "난청, 이명, 중이염, 외이도염 등 귀 질환 전문 진료. 청력 검사 당일 가능.",
          tags: ["이비인후과", "청력검사", "이명"],
          price: "진료비 12,000원~",
          location: "서울시 송파구",
          distance: "4.8km",
          isEvent: false,
          mainCategory: "ear",
          subCategory: "ear-hearing",
          // 추가된 전문 과목 정보
          specialty: "ent", // 이비인후과
          facilityType: "clinic", // 의원
        },
        {
          id: 19,
          type: "medical",
          title: "마인드케어 정신건강의학과",
          image: getMedicalAdImage("all", 2),
          subtitle: "정신건강 전문",
          rating: 4.8,
          reviewCount: 157,
          description:
            "우울증, 불안장애, 공황장애, ADHD 등 정신건강 전문 진료. 비밀보장, 상담 예약 필수.",
          tags: ["정신건강의학과", "우울증", "상담"],
          price: "진료비 25,000원~",
          location: "서울시 서초구",
          distance: "3.5km",
          isEvent: true,
          eventPeriod: "4.1 - 5.31",
          eventContent: "초기 상담 패키지 할인",
          originalPrice: "120,000원",
          discountPrice: "90,000원",
          discountRate: "25%",
          mainCategory: "mental",
          subCategory: "mental-depression",
          // 추가된 전문 과목 정보
          specialty: "psychiatry", // 정신건강의학과
          facilityType: "clinic", // 의원
        },
        {
          id: 20,
          type: "medical",
          title: "알레르기 전문 클리닉",
          image: getMedicalAdImage("all", 3),
          subtitle: "알레르기 질환 전문",
          rating: 4.7,
          reviewCount: 184,
          description:
            "식품 알레르기, 피부 알레르기, 알레르기성 비염, 천식 등 전문 진료 및 검사.",
          tags: ["알레르기내과", "천식", "아토피"],
          price: "진료비 15,000원~",
          location: "서울시 강남구",
          distance: "2.6km",
          isEvent: false,
          mainCategory: "allergy",
          subCategory: "allergy-respiratory",
          // 추가된 전문 과목 정보
          specialty: "allergy", // 알레르기내과
          facilityType: "clinic", // 의원
        },
        {
          id: 21,
          type: "medical",
          title: "감염내과 클리닉",
          image: getMedicalAdImage("all", 4),
          subtitle: "감염질환 전문",
          rating: 4.8,
          reviewCount: 146,
          description:
            "감염성 질환, 열, 원인불명 염증, 면역질환 전문 진료. 신속한 진단과 치료.",
          tags: ["감염내과", "발열", "면역질환"],
          price: "진료비 20,000원~",
          location: "서울시 서초구",
          distance: "3.7km",
          isEvent: true,
          eventPeriod: "4.1 - 4.30",
          eventContent: "면역력 검사 패키지 할인",
          originalPrice: "150,000원",
          discountPrice: "120,000원",
          discountRate: "20%",
          mainCategory: "fever",
          subCategory: "fever-high",
          // 추가된 전문 과목 정보
          specialty: "internal", // 내과
          facilityType: "clinic", // 의원
        },
        // Adding more cosmetic category entries
        {
          id: 22,
          type: "cosmetic",
          title: "더마 스킨 클리닉",
          image: getCosmeticAdImage("all", 4),
          subtitle: "피부관리 전문",
          rating: 4.7,
          reviewCount: 198,
          description:
            "기본 피부관리부터 심화 트리트먼트까지 개인 맞춤형 피부관리 프로그램을 제공합니다.",
          tags: ["피부관리", "모공관리", "수분공급"],
          price: "시술 50,000원~",
          location: "서울시 강남구",
          distance: "2.2km",
          isEvent: true,
          eventPeriod: "4.1 - 4.30",
          eventContent: "첫 방문 고객 기본 관리 할인",
          originalPrice: "80,000원",
          discountPrice: "50,000원",
          discountRate: "37%",
          mainCategory: "skin",
          subCategory: "skin-pore",
          // 새로 추가된 정보
          specialty: "dermatology",
          facilityType: "clinic",
        },
        {
          id: 23,
          type: "cosmetic",
          title: "뷰티 페이스 성형외과",
          image: getCosmeticAdImage("all", 5),
          subtitle: "얼굴 성형 전문",
          rating: 4.9,
          reviewCount: 257,
          description:
            "눈, 코, 윤곽 등 얼굴 성형 맞춤 디자인. 상담부터 수술 후 관리까지 완벽한 케어.",
          tags: ["성형외과", "쌍꺼풀", "코성형"],
          price: "상담 무료",
          location: "서울시 강남구",
          distance: "1.5km",
          isEvent: false,
          mainCategory: "face",
          subCategory: "face-eye",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 24,
          type: "cosmetic",
          title: "슬림바디 컨투어 클리닉",
          image: getCosmeticAdImage("all", 1),
          subtitle: "바디라인 전문",
          rating: 4.6,
          reviewCount: 163,
          description:
            "지방흡입, 바디 리프팅, 셀룰라이트 제거 등 체형 교정 전문. 개인 맞춤 시술 제안.",
          tags: ["지방흡입", "바디컨투어링", "셀룰라이트"],
          price: "상담 무료",
          location: "서울시 서초구",
          distance: "3.2km",
          isEvent: true,
          eventPeriod: "4.15 - 5.15",
          eventContent: "지방흡입 패키지 할인",
          originalPrice: "3,000,000원",
          discountPrice: "2,400,000원",
          discountRate: "20%",
          mainCategory: "body",
          subCategory: "body-liposuction",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 25,
          type: "cosmetic",
          title: "헤어그로우 클리닉",
          image: getCosmeticAdImage("all", 2),
          subtitle: "모발/탈모 전문",
          rating: 4.7,
          reviewCount: 143,
          description:
            "탈모 예방, 두피 관리, 모발 이식 등 모든 모발 관련 시술. 개인 맞춤 프로그램.",
          tags: ["탈모", "두피관리", "모발이식"],
          price: "상담 무료",
          location: "서울시 강남구",
          distance: "2.4km",
          isEvent: false,
          mainCategory: "hair",
          subCategory: "hair-loss",
          // 새로 추가된 정보
          specialty: "dermatology",
          facilityType: "clinic",
        },
        {
          id: 26,
          type: "cosmetic",
          title: "타임리버스 안티에이징 센터",
          image: getCosmeticAdImage("all", 3),
          subtitle: "노화방지 전문",
          rating: 4.8,
          reviewCount: 176,
          description:
            "주름개선, 리프팅, 탄력강화 등 노화방지 전문 시술. 최신 장비와 기술 보유.",
          tags: ["안티에이징", "주름개선", "리프팅"],
          price: "시술 150,000원~",
          location: "서울시 강남구",
          distance: "1.9km",
          isEvent: true,
          eventPeriod: "4.1 - 5.30",
          eventContent: "안티에이징 패키지 특가",
          originalPrice: "450,000원",
          discountPrice: "350,000원",
          discountRate: "22%",
          mainCategory: "antiaging",
          subCategory: "antiaging-wrinkle",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 27,
          type: "cosmetic",
          title: "스마일 치과 미용센터",
          image: getCosmeticAdImage("all", 4),
          subtitle: "치아미용 전문",
          rating: 4.9,
          reviewCount: 215,
          description:
            "치아미백, 라미네이트, 치아교정 등 치아 미용 전문. 디지털 스캔으로 정확한 진단.",
          tags: ["치아미용", "미백", "라미네이트"],
          price: "상담 무료",
          location: "서울시 서초구",
          distance: "3.6km",
          isEvent: true,
          eventPeriod: "4.1 - 4.30",
          eventContent: "치아미백 프로모션",
          originalPrice: "300,000원",
          discountPrice: "200,000원",
          discountRate: "33%",
          mainCategory: "dental",
          subCategory: "dental-whitening",
          // 새로 추가된 정보
          specialty: "dentistry",
          facilityType: "dental",
        },
        {
          id: 28,
          type: "cosmetic",
          title: "인젝션 뷰티 센터",
          image: getCosmeticAdImage("all", 5),
          subtitle: "주사시술 전문",
          rating: 4.7,
          reviewCount: 189,
          description:
            "보톡스, 필러, 지방이식, 메조테라피 등 주사 시술 전문. 의료진의 섬세한 시술.",
          tags: ["보톡스", "필러", "메조테라피"],
          price: "시술 80,000원~",
          location: "서울시 강남구",
          distance: "2.1km",
          isEvent: false,
          mainCategory: "injectable",
          subCategory: "injectable-botox",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 29,
          type: "cosmetic",
          title: "립 아트 클리닉",
          image: getCosmeticAdImage("all", 1),
          subtitle: "입술 성형 전문",
          rating: 4.6,
          reviewCount: 142,
          description:
            "입술 필러, 입술 모양 교정, 입술 라인 개선 등 입술 전문 시술. 자연스러운 볼륨감.",
          tags: ["입술성형", "필러", "입술문신"],
          price: "시술 150,000원~",
          location: "서울시 강남구",
          distance: "2.3km",
          isEvent: true,
          eventPeriod: "4.1 - 5.15",
          eventContent: "입술 필러 프로모션",
          originalPrice: "250,000원",
          discountPrice: "180,000원",
          discountRate: "28%",
          mainCategory: "lip",
          subCategory: "lip-plump",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 30,
          type: "cosmetic",
          title: "클리어 스킨 스튜디오",
          image: getCosmeticAdImage("all", 2),
          subtitle: "흉터/점 제거 전문",
          rating: 4.8,
          reviewCount: 164,
          description:
            "여드름 흉터, 수술 흉터, 점 제거 등 흉터 개선 전문. 맞춤형 치료로 최적의 효과.",
          tags: ["흉터제거", "점제거", "레이저"],
          price: "시술 100,000원~",
          location: "서울시 강남구",
          distance: "2.5km",
          isEvent: false,
          mainCategory: "scar",
          subCategory: "scar-surgical",
          // 새로 추가된 정보
          specialty: "dermatology",
          facilityType: "clinic",
        },
        {
          id: 31,
          type: "cosmetic",
          title: "눈썹 디자인 살롱",
          image: getCosmeticAdImage("all", 3),
          subtitle: "눈썹/속눈썹 전문",
          rating: 4.7,
          reviewCount: 152,
          description:
            "눈썹 문신, 속눈썹 연장, 눈썹 리프팅 등 눈썹 관련 모든 시술. 맞춤 디자인.",
          tags: ["눈썹문신", "속눈썹연장", "반영구"],
          price: "시술 80,000원~",
          location: "서울시 강남구",
          distance: "2.2km",
          isEvent: true,
          eventPeriod: "4.1 - 4.30",
          eventContent: "눈썹 문신 할인",
          originalPrice: "250,000원",
          discountPrice: "180,000원",
          discountRate: "28%",
          mainCategory: "eyebrow",
          subCategory: "eyebrow-tattoo",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 31,
          type: "cosmetic",
          title: "눈썹 디자인 살롱",
          image: getCosmeticAdImage("all", 3),
          subtitle: "눈썹/속눈썹 전문",
          rating: 4.7,
          reviewCount: 152,
          description:
            "눈썹 문신, 속눈썹 연장, 눈썹 리프팅 등 눈썹 관련 모든 시술. 맞춤 디자인.",
          tags: ["눈썹문신", "속눈썹연장", "반영구"],
          price: "시술 80,000원~",
          location: "서울시 강남구",
          distance: "2.2km",
          isEvent: true,
          eventPeriod: "4.1 - 4.30",
          eventContent: "눈썹 문신 할인",
          originalPrice: "250,000원",
          discountPrice: "180,000원",
          discountRate: "28%",
          mainCategory: "eyebrow",
          subCategory: "eyebrow-tattoo",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 33,
          type: "cosmetic",
          title: "슬림 다이어트 클리닉",
          image: getCosmeticAdImage("all", 5),
          subtitle: "다이어트/체중 전문",
          rating: 4.6,
          reviewCount: 178,
          description:
            "체중 관리, 부분 체중 감량, 영양 요법 등 다이어트 전문 프로그램. 개인 맞춤 계획.",
          tags: ["다이어트", "체중관리", "지방분해"],
          price: "프로그램 200,000원~",
          location: "서울시 강남구",
          distance: "2.7km",
          isEvent: true,
          eventPeriod: "4.15 - 5.31",
          eventContent: "다이어트 프로그램 특가",
          originalPrice: "500,000원",
          discountPrice: "350,000원",
          discountRate: "30%",
          mainCategory: "weight",
          subCategory: "weight-management",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        // Filling in remaining sub-categories
        {
          id: 34,
          type: "medical",
          title: "두통 완화 클리닉",
          image: getMedicalAdImage("all", 1),
          subtitle: "두통, 어지럼증 전문",
          rating: 4.5,
          reviewCount: 126,
          description:
            "만성 두통, 어지럼증, 현기증 등 두통 관련 증상 전문 진료와 치료.",
          tags: ["신경과", "두통", "어지럼증"],
          price: "진료비 18,000원~",
          location: "서울시 강남구",
          distance: "2.8km",
          isEvent: false,
          mainCategory: "head",
          subCategory: "head-dizziness",
          // 추가된 전문 과목 정보
          specialty: "neurology", // 신경과
          facilityType: "clinic", // 의원
        },
        {
          id: 35,
          type: "medical",
          title: "가람 호흡기 클리닉",
          image: getMedicalAdImage("all", 2),
          subtitle: "호흡기 질환 전문",
          rating: 4.7,
          reviewCount: 163,
          description:
            "기침, 가래, 비염, 콧물 등 호흡기 질환 전문 진료. 알레르기 검사도 가능합니다.",
          tags: ["호흡기내과", "기침", "알레르기"],
          price: "진료비 15,000원~",
          location: "서울시 송파구",
          distance: "4.3km",
          isEvent: true,
          eventPeriod: "4.1 - 4.30",
          eventContent: "호흡기 종합검진 할인",
          originalPrice: "120,000원",
          discountPrice: "90,000원",
          discountRate: "25%",
          mainCategory: "cold",
          subCategory: "cold-cough",
          // 추가된 전문 과목 정보
          specialty: "pulmonology", // 호흡기내과
          facilityType: "clinic", // 의원
        },
        {
          id: 36,
          type: "medical",
          title: "위장 편안 내과",
          image: getMedicalAdImage("all", 3),
          subtitle: "소화기 질환 전문",
          rating: 4.6,
          reviewCount: 145,
          description:
            "위장 통증, 복통, 메스꺼움, 구토 등 위장 관련 증상 전문 진료. 신속한 대응.",
          tags: ["소화기내과", "위장통증", "소화불량"],
          price: "진료비 18,000원~",
          location: "서울시 강남구",
          distance: "2.5km",
          isEvent: false,
          mainCategory: "stomach",
          subCategory: "stomach-nausea",
          // 추가된 전문 과목 정보
          specialty: "gastroenterology", // 소화기내과
          facilityType: "clinic", // 의원
        },
        {
          id: 37,
          type: "cosmetic",
          title: "화이트 스킨 클리닉",
          image: getCosmeticAdImage("all", 1),
          subtitle: "피부 미백 전문",
          rating: 4.8,
          reviewCount: 173,
          description:
            "피부 톤 개선, 미백 관리, 색소 침착 치료로 밝고 균일한 피부톤을 만들어 드립니다.",
          tags: ["미백", "색소치료", "톤업"],
          price: "시술 100,000원~",
          location: "서울시 강남구",
          distance: "2.1km",
          isEvent: true,
          eventPeriod: "4.1 - 5.15",
          eventContent: "미백 프로그램 특가",
          originalPrice: "300,000원",
          discountPrice: "200,000원",
          discountRate: "33%",
          mainCategory: "skin",
          subCategory: "skin-whitening",
          // 새로 추가된 정보
          specialty: "dermatology",
          facilityType: "clinic",
        },
        {
          id: 38,
          type: "cosmetic",
          title: "코성형 전문 클리닉",
          image: getCosmeticAdImage("all", 2),
          subtitle: "코 성형 전문",
          rating: 4.9,
          reviewCount: 248,
          description:
            "비절개, 절개, 매부리코, 콧대 등 다양한 코 성형 전문. 3D 시뮬레이션으로 미리 확인.",
          tags: ["코성형", "비절개", "콧대"],
          price: "상담 무료",
          location: "서울시 강남구",
          distance: "1.8km",
          isEvent: false,
          mainCategory: "face",
          subCategory: "face-nose",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 39,
          type: "cosmetic",
          title: "슬림 셀룰라이트 케어",
          image: getCosmeticAdImage("all", 3),
          subtitle: "셀룰라이트 전문",
          rating: 4.6,
          reviewCount: 156,
          description:
            "셀룰라이트 제거, 지방분해, 바디 라인 개선을 위한 맞춤형 프로그램을 제공합니다.",
          tags: ["셀룰라이트", "바디관리", "지방분해"],
          price: "시술 150,000원~",
          location: "서울시 서초구",
          distance: "3.4km",
          isEvent: true,
          eventPeriod: "4.15 - 5.31",
          eventContent: "셀룰라이트 관리 패키지",
          originalPrice: "450,000원",
          discountPrice: "350,000원",
          discountRate: "22%",
          mainCategory: "body",
          subCategory: "body-cellulite",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 40,
          type: "cosmetic",
          title: "헤어 트랜스플랜트 센터",
          image: getCosmeticAdImage("all", 4),
          subtitle: "모발 이식 전문",
          rating: 4.8,
          reviewCount: 162,
          description:
            "최신 FUE 방식의 자연스러운 모발 이식. 탈모 부위에 따른 맞춤형 디자인과 시술.",
          tags: ["모발이식", "탈모", "두피케어"],
          price: "상담 무료",
          location: "서울시 강남구",
          distance: "2.3km",
          isEvent: false,
          mainCategory: "hair",
          subCategory: "hair-transplant",
          // 새로 추가된 정보
          specialty: "dermatology",
          facilityType: "clinic",
        },
        {
          id: 41,
          type: "cosmetic",
          title: "네오 스킨 클리닉",
          image: getCosmeticAdImage("all", 5),
          subtitle: "탄력 강화 전문",
          rating: 4.7,
          reviewCount: 148,
          description:
            "콜라겐 촉진, 탄력 강화, 피부 리프팅을 위한 최신 시술. 노화 방지 효과 탁월.",
          tags: ["탄력강화", "콜라겐", "리프팅"],
          price: "시술 180,000원~",
          location: "서울시 강남구",
          distance: "2.4km",
          isEvent: true,
          eventPeriod: "4.1 - 5.31",
          eventContent: "탄력 케어 패키지 할인",
          originalPrice: "500,000원",
          discountPrice: "350,000원",
          discountRate: "30%",
          mainCategory: "antiaging",
          subCategory: "antiaging-tightening",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 42,
          type: "cosmetic",
          title: "스마일라인 치과",
          image: getCosmeticAdImage("all", 1),
          subtitle: "치아 교정 전문",
          rating: 4.9,
          reviewCount: 226,
          description:
            "투명 교정, 설측 교정, 부분 교정 등 다양한 치아 교정 방법. 개인별 맞춤 교정.",
          tags: ["치아교정", "투명교정", "스마일라인"],
          price: "상담 무료",
          location: "서울시 서초구",
          distance: "3.5km",
          isEvent: false,
          mainCategory: "dental",
          subCategory: "dental-alignment",
          // 새로 추가된 정보
          specialty: "dentistry",
          facilityType: "dental",
        },
        {
          id: 43,
          type: "cosmetic",
          title: "실루엣 메디컬 클리닉",
          image: getCosmeticAdImage("all", 2),
          subtitle: "실 리프팅 전문",
          rating: 4.8,
          reviewCount: 187,
          description:
            "최신 PDO, 콜라겐 실 등을 이용한 비수술 리프팅. 자연스러운 얼굴 윤곽 개선.",
          tags: ["실리프팅", "비수술", "콜라겐실"],
          price: "시술 250,000원~",
          location: "서울시 강남구",
          distance: "2.1km",
          isEvent: true,
          eventPeriod: "4.15 - 5.15",
          eventContent: "첫 방문 실 리프팅 할인",
          originalPrice: "450,000원",
          discountPrice: "350,000원",
          discountRate: "22%",
          mainCategory: "injectable",
          subCategory: "injectable-thread",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 44,
          type: "cosmetic",
          title: "립 볼륨 아트 클리닉",
          image: getCosmeticAdImage("all", 3),
          subtitle: "입술 볼륨 전문",
          rating: 4.7,
          reviewCount: 153,
          description:
            "입술 볼륨 필러, 입술 라인 교정으로 자연스럽고 매력적인 입술을 만들어 드립니다.",
          tags: ["입술필러", "볼륨", "입술라인"],
          price: "시술 180,000원~",
          location: "서울시 강남구",
          distance: "2.2km",
          isEvent: false,
          mainCategory: "lip",
          subCategory: "lip-volume",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 45,
          type: "cosmetic",
          title: "아큐어 흉터 클리닉",
          image: getCosmeticAdImage("all", 4),
          subtitle: "화상 흉터 전문",
          rating: 4.8,
          reviewCount: 142,
          description:
            "화상 흉터, 수술 흉터, 사고 흉터 등 다양한 흉터 치료. 최신 레이저 기술 활용.",
          tags: ["흉터치료", "화상흉터", "레이저"],
          price: "상담 무료",
          location: "서울시 서초구",
          distance: "3.6km",
          isEvent: true,
          eventPeriod: "4.1 - 5.31",
          eventContent: "흉터 치료 프로그램 할인",
          originalPrice: "500,000원",
          discountPrice: "400,000원",
          discountRate: "20%",
          mainCategory: "scar",
          subCategory: "scar-burn",
          // 새로 추가된 정보
          specialty: "dermatology",
          facilityType: "clinic",
        },
        {
          id: 46,
          type: "cosmetic",
          title: "아이브로우 디자인 살롱",
          image: getCosmeticAdImage("all", 5),
          subtitle: "눈썹 디자인 전문",
          rating: 4.6,
          reviewCount: 158,
          description:
            "눈썹 디자인, 눈썹 정리, 반영구 눈썹으로 얼굴형에 맞는 완벽한 눈썹을 찾아드립니다.",
          tags: ["눈썹", "눈썹정리", "반영구"],
          price: "시술 80,000원~",
          location: "서울시 강남구",
          distance: "2.3km",
          isEvent: false,
          mainCategory: "eyebrow",
          subCategory: "eyebrow-shape",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 47,
          type: "cosmetic",
          title: "베인 케어 클리닉",
          image: getCosmeticAdImage("all", 1),
          subtitle: "혈관 레이저 전문",
          rating: 4.7,
          reviewCount: 146,
          description:
            "실핏줄, 다리 정맥류, 홍조 등 혈관성 피부 문제 전문 치료. 정확한 타겟팅 레이저.",
          tags: ["혈관레이저", "정맥류", "홍조"],
          price: "시술 150,000원~",
          location: "서울시 서초구",
          distance: "3.4km",
          isEvent: true,
          eventPeriod: "4.15 - 5.15",
          eventContent: "혈관 레이저 패키지 할인",
          originalPrice: "350,000원",
          discountPrice: "280,000원",
          discountRate: "20%",
          mainCategory: "laser",
          subCategory: "laser-vein",
          // 새로 추가된 정보
          specialty: "dermatology",
          facilityType: "clinic",
        },
        {
          id: 48,
          type: "cosmetic",
          title: "근육 밸런스 클리닉",
          image: getCosmeticAdImage("all", 2),
          subtitle: "근육 강화 전문",
          rating: 4.8,
          reviewCount: 176,
          description:
            "비수술적 근육 강화, 체형 개선, 식이요법을 통한 건강한 다이어트 프로그램 제공.",
          tags: ["근육강화", "체형교정", "다이어트"],
          price: "프로그램 250,000원~",
          location: "서울시 강남구",
          distance: "2.5km",
          isEvent: false,
          mainCategory: "weight",
          subCategory: "weight-muscle",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 49,
          type: "cosmetic",
          title: "아큐어 흉터 클리닉",
          image: getCosmeticAdImage("all", 4),
          subtitle: "화상 흉터 전문",
          rating: 4.8,
          reviewCount: 142,
          description:
            "화상 흉터, 수술 흉터, 사고 흉터 등 다양한 흉터 치료. 최신 레이저 기술 활용.",
          tags: ["흉터치료", "화상흉터", "레이저"],
          price: "상담 무료",
          location: "서울시 서초구",
          distance: "3.6km",
          isEvent: true,
          eventPeriod: "4.1 - 5.31",
          eventContent: "흉터 치료 프로그램 할인",
          originalPrice: "500,000원",
          discountPrice: "400,000원",
          discountRate: "20%",
          mainCategory: "scar",
          subCategory: "scar-burn",
          // 새로 추가된 정보
          specialty: "dermatology",
          facilityType: "clinic",
        },
        {
          id: 50,
          type: "cosmetic",
          title: "아이브로우 디자인 살롱",
          image: getCosmeticAdImage("all", 5),
          subtitle: "눈썹 디자인 전문",
          rating: 4.6,
          reviewCount: 158,
          description:
            "눈썹 디자인, 눈썹 정리, 반영구 눈썹으로 얼굴형에 맞는 완벽한 눈썹을 찾아드립니다.",
          tags: ["눈썹", "눈썹정리", "반영구"],
          price: "시술 80,000원~",
          location: "서울시 강남구",
          distance: "2.3km",
          isEvent: false,
          mainCategory: "eyebrow",
          subCategory: "eyebrow-shape",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 51,
          type: "medical",
          title: "기억력 클리닉",
          image: getMedicalAdImage("all", 5),
          subtitle: "기억력/인지 전문",
          rating: 4.6,
          reviewCount: 121,
          description:
            "기억력 저하, 집중력 문제, 인지 기능 약화 등 기억 관련 치료 및 관리 프로그램.",
          tags: ["신경과", "기억력", "인지기능"],
          price: "진료비 25,000원~",
          location: "서울시 서초구",
          distance: "3.8km",
          isEvent: true,
          eventPeriod: "4.1 - 4.30",
          eventContent: "인지 기능 검사 할인",
          originalPrice: "150,000원",
          discountPrice: "100,000원",
          discountRate: "33%",
          mainCategory: "head",
          subCategory: "head-memory",
          // 새로 추가된 정보
          specialty: "neurology",
          facilityType: "clinic",
        },
        {
          id: 52,
          type: "medical",
          title: "호흡기 케어 의원",
          image: getMedicalAdImage("all", 1),
          subtitle: "호흡 곤란 전문",
          rating: 4.7,
          reviewCount: 158,
          description:
            "호흡 곤란, 숨참, 천식 등 호흡기 질환 전문 진료. 정확한 진단과 맞춤 치료.",
          tags: ["호흡기내과", "호흡곤란", "천식"],
          price: "진료비 18,000원~",
          location: "서울시 강남구",
          distance: "2.6km",
          isEvent: false,
          mainCategory: "cold",
          subCategory: "cold-hard-breath",
          // 새로 추가된 정보
          specialty: "pulmonology",
          facilityType: "clinic",
        },
        {
          id: 53,
          type: "medical",
          title: "벨리케어 소화기 클리닉",
          image: getMedicalAdImage("all", 2),
          subtitle: "복부 통증 전문",
          rating: 4.8,
          reviewCount: 173,
          description:
            "급성/만성 복통, 과민성 대장 증후군, 소화불량 등 복부 통증 전문 진료.",
          tags: ["소화기내과", "복통", "장염"],
          price: "진료비 20,000원~",
          location: "서울시 강남구",
          distance: "2.4km",
          isEvent: true,
          eventPeriod: "4.15 - 5.15",
          eventContent: "복부 초음파 검사 할인",
          originalPrice: "120,000원",
          discountPrice: "90,000원",
          discountRate: "25%",
          mainCategory: "stomach",
          subCategory: "stomach-pain",
          // 새로 추가된 정보
          specialty: "gastroenterology",
          facilityType: "clinic",
        },
        {
          id: 54,
          type: "medical",
          title: "클린 피부 클리닉",
          image: getMedicalAdImage("all", 3),
          subtitle: "피부 가려움증 전문",
          rating: 4.6,
          reviewCount: 138,
          description:
            "만성 가려움증, 피부 건조, 아토피, 알레르기성 피부염 등 전문 진료 및 치료.",
          tags: ["피부과", "가려움증", "아토피"],
          price: "진료비 15,000원~",
          location: "서울시 서초구",
          distance: "3.5km",
          isEvent: false,
          mainCategory: "skin",
          subCategory: "skin-itchy",
          // 새로 추가된 정보
          specialty: "dermatology",
          facilityType: "clinic",
        },
        {
          id: 55,
          type: "medical",
          title: "관절 모션 클리닉",
          image: getMedicalAdImage("all", 4),
          subtitle: "관절 강직 전문",
          rating: 4.7,
          reviewCount: 156,
          description:
            "관절 뻣뻣함, 움직임 제한, 관절염 등 관절 기능 장애 전문 진료 및 물리치료.",
          tags: ["정형외과", "관절강직", "물리치료"],
          price: "진료비 18,000원~",
          location: "서울시 강남구",
          distance: "2.7km",
          isEvent: true,
          eventPeriod: "4.1 - 4.30",
          eventContent: "관절 기능 회복 프로그램",
          originalPrice: "300,000원",
          discountPrice: "240,000원",
          discountRate: "20%",
          mainCategory: "joint",
          subCategory: "joint-stiffness",
          // 새로 추가된 정보
          specialty: "orthopedics",
          facilityType: "clinic",
        },
        {
          id: 56,
          type: "medical",
          title: "하트 리듬 클리닉",
          image: getMedicalAdImage("all", 5),
          subtitle: "심장 두근거림 전문",
          rating: 4.9,
          reviewCount: 187,
          description:
            "심장 두근거림, 부정맥, 심계항진 등 심장 리듬 관련 전문 진료 및 정밀 검사.",
          tags: ["심장내과", "부정맥", "심장검사"],
          price: "진료비 25,000원~",
          location: "서울시 강남구",
          distance: "2.2km",
          isEvent: false,
          mainCategory: "chest",
          subCategory: "chest-palpitation",
          // 새로 추가된 정보
          specialty: "cardiology",
          facilityType: "clinic",
        },
        {
          id: 57,
          type: "medical",
          title: "슬립 웰 클리닉",
          image: getMedicalAdImage("all", 1),
          subtitle: "수면 무호흡증 전문",
          rating: 4.7,
          reviewCount: 142,
          description:
            "수면 무호흡증, 코골이, 수면 중 호흡 장애 등 수면호흡장애 전문 진료 및 치료.",
          tags: ["수면의학과", "코골이", "수면무호흡"],
          price: "진료비 20,000원~",
          location: "서울시 서초구",
          distance: "3.4km",
          isEvent: true,
          eventPeriod: "4.15 - 5.15",
          eventContent: "수면다원검사 할인",
          originalPrice: "350,000원",
          discountPrice: "280,000원",
          discountRate: "20%",
          mainCategory: "sleep",
          subCategory: "sleep-apnea",
          // 새로 추가된 정보
          specialty: "neurology",
          facilityType: "clinic",
        },
        {
          id: 58,
          type: "medical",
          title: "아이케어 안과 클리닉",
          image: getMedicalAdImage("all", 2),
          subtitle: "안구 건조증 전문",
          rating: 4.8,
          reviewCount: 176,
          description:
            "안구 건조증, 눈물막 검사, 안구 표면 질환 등 눈 건조 관련 전문 진료 및 치료.",
          tags: ["안과", "안구건조증", "눈물검사"],
          price: "진료비 15,000원~",
          location: "서울시 강남구",
          distance: "2.5km",
          isEvent: false,
          mainCategory: "eye",
          subCategory: "eye-dry",
          // 새로 추가된 정보
          specialty: "ophthalmology",
          facilityType: "clinic",
        },
        {
          id: 59,
          type: "medical",
          title: "이어 클리닉 센터",
          image: getMedicalAdImage("all", 3),
          subtitle: "귀 이명 전문",
          rating: 4.7,
          reviewCount: 159,
          description:
            "이명, 귀 울림, 청력 장애 등 귀 관련 전문 진료. 최신 청력 검사 장비 보유.",
          tags: ["이비인후과", "이명", "청력검사"],
          price: "진료비 18,000원~",
          location: "서울시 서초구",
          distance: "3.6km",
          isEvent: true,
          eventPeriod: "4.1 - 5.31",
          eventContent: "이명 치료 프로그램 할인",
          originalPrice: "250,000원",
          discountPrice: "200,000원",
          discountRate: "20%",
          mainCategory: "ear",
          subCategory: "ear-ringing",
          // 새로 추가된 정보
          specialty: "ent",
          facilityType: "clinic",
        },
        {
          id: 60,
          type: "medical",
          title: "마인드 포커스 센터",
          image: getMedicalAdImage("all", 4),
          subtitle: "집중력 장애 전문",
          rating: 4.6,
          reviewCount: 132,
          description:
            "집중력 저하, ADHD, 학습 장애 등 집중력 관련 문제 진단 및 치료. 맞춤형 상담.",
          tags: ["정신건강의학과", "집중력", "ADHD"],
          price: "진료비 25,000원~",
          location: "서울시 강남구",
          distance: "2.4km",
          isEvent: false,
          mainCategory: "mental",
          subCategory: "mental-focus",
          // 새로 추가된 정보
          specialty: "psychiatry",
          facilityType: "clinic",
        },
        // 61-65번 추가 데이터
        {
          id: 61,
          type: "cosmetic",
          title: "아이브로우 디자인 살롱",
          image: getCosmeticAdImage("all", 3),
          subtitle: "눈썹 디자인 전문",
          rating: 4.6,
          reviewCount: 158,
          description:
            "눈썹 디자인, 눈썹 정리, 반영구 눈썹으로 얼굴형에 맞는 완벽한 눈썹을 찾아드립니다.",
          tags: ["눈썹", "눈썹정리", "반영구"],
          price: "시술 80,000원~",
          location: "서울시 강남구",
          distance: "2.3km",
          isEvent: false,
          mainCategory: "eyebrow",
          subCategory: "eyebrow-shape",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 62,
          type: "cosmetic",
          title: "베인 케어 클리닉",
          image: getCosmeticAdImage("all", 1),
          subtitle: "혈관 레이저 전문",
          rating: 4.7,
          reviewCount: 146,
          description:
            "실핏줄, 다리 정맥류, 홍조 등 혈관성 피부 문제 전문 치료. 정확한 타겟팅 레이저.",
          tags: ["혈관레이저", "정맥류", "홍조"],
          price: "시술 150,000원~",
          location: "서울시 서초구",
          distance: "3.4km",
          isEvent: true,
          eventPeriod: "4.15 - 5.15",
          eventContent: "혈관 레이저 패키지 할인",
          originalPrice: "350,000원",
          discountPrice: "280,000원",
          discountRate: "20%",
          mainCategory: "laser",
          subCategory: "laser-vein",
          // 새로 추가된 정보
          specialty: "dermatology",
          facilityType: "clinic",
        },
        {
          id: 63,
          type: "cosmetic",
          title: "근육 밸런스 클리닉",
          image: getCosmeticAdImage("all", 2),
          subtitle: "근육 강화 전문",
          rating: 4.8,
          reviewCount: 176,
          description:
            "비수술적 근육 강화, 체형 개선, 식이요법을 통한 건강한 다이어트 프로그램 제공.",
          tags: ["근육강화", "체형교정", "다이어트"],
          price: "프로그램 250,000원~",
          location: "서울시 강남구",
          distance: "2.5km",
          isEvent: false,
          mainCategory: "weight",
          subCategory: "weight-muscle",
          // 새로 추가된 정보
          specialty: "plastic",
          facilityType: "clinic",
        },
        {
          id: 64,
          type: "cosmetic",
          title: "에센셜 스킨케어",
          image: getCosmeticAdImage("all", 4),
          subtitle: "맞춤형 피부 진단 관리",
          rating: 4.6,
          reviewCount: 168,
          description:
            "피부 진단부터 클렌징, 각질 관리, 마사지, 팩까지 개인 피부 상태에 맞는 맞춤형 기본 관리를 제공합니다.",
          tags: ["피부진단", "맞춤관리", "기초케어"],
          price: "시술 90,000원~",
          location: "서울시 송파구",
          distance: "4.5km",
          isEvent: false,
          mainCategory: "skin",
          subCategory: "skin-basic",
          // 새로 추가된 정보
          specialty: "dermatology",
          facilityType: "clinic",
        },
        {
          id: 65,
          type: "cosmetic",
          title: "내추럴 스킨 테라피",
          image: getCosmeticAdImage("all", 5),
          subtitle: "자연주의 피부 관리",
          rating: 4.8,
          reviewCount: 184,
          description:
            "천연 성분으로 만든 제품만을 사용하여 피부에 자극 없이 건강한 광채를 되찾는 기본 피부 관리 프로그램을 제공합니다.",
          tags: ["자연주의", "저자극", "기초관리"],
          price: "시술 95,000원~",
          location: "서울시 마포구",
          distance: "3.7km",
          isEvent: true,
          eventPeriod: "4.20 - 5.20",
          eventContent: "천연 성분 케어 패키지",
          originalPrice: "150,000원",
          discountPrice: "110,000원",
          discountRate: "27%",
          mainCategory: "skin",
          subCategory: "skin-basic",
          // 새로 추가된 정보
          specialty: "dermatology",
          facilityType: "clinic",
        },
      ],
      facilityInfo: {
        gym: {
          name: t("facility.examples.location1"),
          rating: 4.5,
          location: t("facility.examples.address1"),
          facilities: [
            t("facility.amenities.shower"),
            t("facility.amenities.uniform"),
            t("facility.amenities.locker"),
            t("facility.amenities.parking"),
          ],
          plans: [
            {
              duration: "3 " + t("common.units.monthCount"),
              monthlyPrice: 60000,
              totalPrice: 180000,
            },
            {
              duration: "6 " + t("common.units.monthCount"),
              monthlyPrice: 55000,
              totalPrice: 330000,
            },
            {
              duration: "12 " + t("common.units.monthCount"),
              monthlyPrice: 50000,
              totalPrice: 600000,
            },
          ],
        },
        pilates: {
          name: t("facility.examples.name2"),
          rating: 4.8,
          location: t("facility.examples.address1"),
          facilities: [
            t("facility.amenities.shower"),
            t("facility.amenities.uniform"),
            t("facility.amenities.locker"),
            t("facility.amenities.parking"),
          ],
          plans: [
            {
              duration: "3 " + t("common.units.monthCount"),
              monthlyPrice: 150000,
              totalPrice: 450000,
            },
            {
              duration: "6 " + t("common.units.monthCount"),
              monthlyPrice: 140000,
              totalPrice: 840000,
            },
            {
              duration: "12 " + t("common.units.monthCount"),
              monthlyPrice: 130000,
              totalPrice: 1560000,
            },
          ],
        },
        jiujitsu: {
          name: t("facility.examples.name3"),
          rating: 4.7,
          location: t("facility.examples.address1"),
          facilities: [
            t("facility.amenities.shower"),
            t("facility.amenities.uniform"),
            t("facility.amenities.locker"),
            t("facility.amenities.parking"),
          ],
          plans: [
            {
              duration: "3 " + t("common.units.monthCount"),
              monthlyPrice: 120000,
              totalPrice: 360000,
            },
            {
              duration: "6 " + t("common.units.monthCount"),
              monthlyPrice: 110000,
              totalPrice: 660000,
            },
            {
              duration: "12 " + t("common.units.monthCount"),
              monthlyPrice: 100000,
              totalPrice: 1200000,
            },
          ],
        },
      },
      gymReviews: [
        {
          id: 1,
          author: "WorkoutLover",
          date: "2024-02-10",
          rating: 5,
          content: t("review.gym.example_2.content"),
        },
        {
          id: 2,
          author: "Dieter",
          date: "2024-02-09",
          rating: 4,
          content: t("review.gym.example_3.content"),
        },
      ],
      gymData: {
        헬스: Array.from({ length: 15 }, (_, i) => ({
          id: i + 1,
          name:
            i18n.language == "en"
              ? `${t("facility.examples.name1")} ${t(
                  "facility.branch.number"
                )} ${i + 1}`
              : `${t("facility.examples.name1")} ${i + 1}${t(
                  "facility.branch.number"
                )}`,
          location: t("facility.examples.address1"),
          rating: 4.5,
          price: "80,000",
          type: "gym",
        })),
        필라테스: Array.from({ length: 4 }, (_, i) => ({
          id: i + 1,
          name:
            i18n.language == "en"
              ? `${t("facility.examples.name2")} ${t(
                  "facility.branch.number"
                )} ${i + 1}`
              : `${t("facility.examples.name2")} ${i + 1}${t(
                  "facility.branch.number"
                )}`,
          location: t("facility.examples.address1"),
          rating: 4.8,
          price: "150,000",
          type: "pilates",
        })),
        주짓수: Array.from({ length: 3 }, (_, i) => ({
          id: i + 1,
          name:
            i18n.language == "en"
              ? `${t("facility.examples.name3")} ${t(
                  "facility.branch.number"
                )} ${i + 1}`
              : `${t("facility.examples.name3")} ${i + 1}${t(
                  "facility.branch.number"
                )}`,
          location: t("facility.examples.address1"),
          rating: 4.7,
          price: "120,000",
          type: "jiujitsu",
        })),
      },
      trainerInfo: {
        gym: {
          name: t("trainer.examples.name1"),
          rating: 4.8,
          specialties:
            t("trainer.specialties.weightLoss") +
            ", " +
            t("trainer.specialties.bodybuilding"),
          experience: 5 + " " + t("common.year"),
          certifications: ["생활스포츠지도사 2급", "NSCA-CPT", "KATA-PTS"],
          plans: [
            {
              sessions: 30 + " " + t("trainer.sessions"),
              pricePerSession: "60,000",
              totalPrice: "1,800,000",
            },
            {
              sessions: 20 + " " + t("trainer.sessions"),
              pricePerSession: "70,000",
              totalPrice: "1,400,000",
            },
            {
              sessions: "10 " + t("trainer.sessions"),
              pricePerSession: "80,000",
              totalPrice: "800,000",
            },
          ],
        },
        pilates: {
          name: t("trainer.examples.name2"),
          rating: 4.9,
          specialties:
            t("trainer.specialties.posture") +
            ", " +
            t("trainer.specialties.rehabilitation"),
          experience: 7 + " " + t("common.year"),
          certifications: [
            "필라테스 지도자 자격증",
            "재활 트레이닝 전문가",
            "매트 필라테스 자격증",
          ],
          plans: [
            {
              sessions: 30 + " " + t("trainer.sessions"),
              pricePerSession: "70,000",
              totalPrice: "2,100,000",
            },
            {
              sessions: 20 + " " + t("trainer.sessions"),
              pricePerSession: "80,000",
              totalPrice: "1,600,000",
            },
            {
              sessions: "10 " + t("trainer.sessions"),
              pricePerSession: "90,000",
              totalPrice: "900,000",
            },
          ],
        },
        jiujitsu: {
          name: t("trainer.examples.name3"),
          rating: 4.7,
          specialties:
            t("trainer.specialties.jiujitsu") +
            ", " +
            t("trainer.specialties.grappling"),
          experience: "6년",
          certifications: [
            "주짓수 블랙벨트",
            "종합격투기 지도자 자격증",
            "퍼스널 트레이닝 자격증",
          ],
          plans: [
            {
              sessions: 30 + " " + t("trainer.sessions"),
              pricePerSession: "65,000",
              totalPrice: "1,950,000",
            },
            {
              sessions: 20 + " " + t("trainer.sessions"),
              pricePerSession: "75,000",
              totalPrice: "1,500,000",
            },
            {
              sessions: "10 " + t("trainer.sessions"),
              pricePerSession: "85,000",
              totalPrice: "850,000",
            },
          ],
        },
      },
      trainerReviews: [
        {
          id: 1,
          author: "PTWanna",
          date: "2024-02-10",
          rating: 5,
          content: t("review.gym.example_4.content"),
        },
        {
          id: 2,
          author: "Dieter",
          date: "2024-02-09",
          rating: 4,
          content: t("review.gym.example_5.content"),
        },
        // Add more reviews as needed
      ],
      trainerData: {
        헬스: Array.from({ length: 8 }, (_, i) => ({
          id: i + 1,
          name: `${t("trainer.examples.name1")} ${i + 1}`,
          specialties: `${t("trainer.specialties.weightLoss")}, ${t(
            "trainer.specialties.bodybuilding"
          )}`, //"체중감량, 근력강화",
          rating: 4.8,
          price: "100,000",
          type: "gym",
        })),
        필라테스: Array.from({ length: 5 }, (_, i) => ({
          id: i + 1,
          name: `${t("trainer.examples.name2")} ${i + 1}`,
          specialties: `${t("trainer.specialties.posture")}, ${t(
            "trainer.specialties.rehabilitation"
          )}`,
          rating: 4.9,
          price: "120,000",
          type: "pilates",
        })),
        주짓수: Array.from({ length: 3 }, (_, i) => ({
          id: i + 1,
          name: `${t("trainer.examples.name3")} ${i + 1}`,
          specialties: `${t("trainer.specialties.jiujitsu")}, ${t(
            "trainer.specialties.grappling"
          )}`,
          rating: 4.7,
          price: "110,000",
          type: "jiujitsu",
        })),
      },
      communityData: {
        coach: Array.from({ length: 10 }, (_, i) => ({
          id: i + 1,
          name: `Dieter ${i + 1}`,
          title: `${t("community.gym.example3.title")}  ${i + 1}`,
          content: `${t("community.gym.example3.content")}  ${i + 1}`,
          comment: `${t("community.gym.example3.comment")}  ${i + 1}`,
          rating: 4.8,
          date: "2024-02-06",
          likeCount: 24,
          commentCount: 17,
        })),
        medical: Array.from({ length: 10 }, (_, i) => ({
          id: i + 1,
          name: `Dieter ${i + 1}`,
          title: `${t("community.medical.example3.title")}  ${i + 1}`,
          content: `${t("community.medical.example3.content")}  ${i + 1}`,
          comment: `${t("community.medical.example3.comment")}  ${i + 1}`,
          rating: 4.8,
          date: "2024-02-06",
          likeCount: 24,
          commentCount: 17,
        })),
        plastic: Array.from({ length: 10 }, (_, i) => ({
          id: i + 1,
          name: `Dieter ${i + 1}`,
          title: `${t("community.plastic.example3.title")}  ${i + 1}`,
          content: `${t("community.plastic.example3.content")}  ${i + 1}`,
          comment: `${t("community.plastic.example3.comment")}  ${i + 1}`,
          rating: 4.8,
          date: "2024-02-06",
          likeCount: 24,
          commentCount: 17,
        })),
      },
    });
  }, [t, i18n.language]);

  return <DataContext.Provider value={data}>{children}</DataContext.Provider>;
};

export const useData = () => useContext(DataContext);
