/**
 * 전라북도 주요 시/군별 동/읍/면 정보
 */
export const jeonbukSubRegions = {
  // 전라북도 전주시의 구별 동
  "jeonbuk.jeonju": {
    // 전주시 완산구
    wansan: [
      {
        id: "jungang",
        label: "중앙동",
        medicalSpecialty: ["general", "internal"],
      },
      { id: "nambu", label: "풍남동", medicalSpecialty: ["general"] },
      { id: "pungnam", label: "노송동", medicalSpecialty: ["general"] },
      { id: "nosong", label: "완산동", medicalSpecialty: ["general"] },
      { id: "wansan", label: "동서학동", medicalSpecialty: ["general"] },
      { id: "dongsehak", label: "서서학동", medicalSpecialty: ["general"] },
      { id: "seosehak", label: "효자1동", medicalSpecialty: ["general"] },
      { id: "hyoja1", label: "효자2동", medicalSpecialty: ["general"] },
      { id: "hyoja2", label: "효자3동", medicalSpecialty: ["general"] },
      {
        id: "hyoja3",
        label: "효자4동",
        medicalSpecialty: ["general", "dermatology"],
      },
      { id: "hyoja4", label: "효자5동", medicalSpecialty: ["general"] },
      { id: "hyoja5", label: "삼천1동", medicalSpecialty: ["general"] },
      { id: "samcheon1", label: "삼천2동", medicalSpecialty: ["general"] },
      { id: "samcheon2", label: "삼천3동", medicalSpecialty: ["general"] },
      { id: "samcheon3", label: "평화1동", medicalSpecialty: ["general"] },
      { id: "pyeonghwa1", label: "평화2동", medicalSpecialty: ["general"] },
      { id: "pyeonghwa2", label: "서신동", medicalSpecialty: ["general"] },
      { id: "seosin", label: "서신동", medicalSpecialty: ["general"] },
    ],

    // 전주시 덕진구
    deokjin: [
      { id: "dukjin", label: "덕진동", medicalSpecialty: ["general"] },
      { id: "palbok", label: "팔복동", medicalSpecialty: ["general"] },
      { id: "dongsan", label: "조촌동", medicalSpecialty: ["general"] },
      { id: "jochon", label: "송천1동", medicalSpecialty: ["general"] },
      {
        id: "songcheon1",
        label: "송천2동",
        medicalSpecialty: ["general", "internal"],
      },
      { id: "songcheon2", label: "우아1동", medicalSpecialty: ["general"] },
      { id: "ua1", label: "우아2동", medicalSpecialty: ["general"] },
      { id: "ua2", label: "인후1동", medicalSpecialty: ["general"] },
      { id: "inhu1", label: "인후2동", medicalSpecialty: ["general"] },
      { id: "inhu2", label: "인후3동", medicalSpecialty: ["general"] },
      { id: "inhu3", label: "금암1동", medicalSpecialty: ["general"] },
      { id: "geumam1", label: "금암2동", medicalSpecialty: ["general"] },
      { id: "geumam2", label: "진북동", medicalSpecialty: ["general"] },
      { id: "jinbuk", label: "호성동", medicalSpecialty: ["general"] },
      { id: "hoseong", label: "송천동", medicalSpecialty: ["general"] },
      {
        id: "songcheon",
        label: "전북대",
        medicalSpecialty: ["general", "hospital"],
      },
    ],
  },

  // 전라북도 군산시의 동/읍/면
  "jeonbuk.gunsan": [
    { id: "sinyong", label: "신영동", medicalSpecialty: ["general"] },
    { id: "wolmyeong", label: "월명동", medicalSpecialty: ["general"] },
    {
      id: "jungang",
      label: "중앙동",
      medicalSpecialty: ["general", "internal"],
    },
    { id: "haewundae", label: "해신동", medicalSpecialty: ["general"] },
    { id: "haesin", label: "월명동", medicalSpecialty: ["general"] },
    { id: "wolmyeong", label: "신풍동", medicalSpecialty: ["general"] },
    { id: "sinpung", label: "삼학동", medicalSpecialty: ["general"] },
    { id: "samhak", label: "선양동", medicalSpecialty: ["general"] },
    { id: "seonyang", label: "소룡동", medicalSpecialty: ["general"] },
    { id: "soryong", label: "미성동", medicalSpecialty: ["general"] },
    { id: "miseong", label: "나운1동", medicalSpecialty: ["general"] },
    { id: "naun1", label: "나운2동", medicalSpecialty: ["general"] },
    { id: "naun2", label: "나운3동", medicalSpecialty: ["general"] },
    { id: "naun3", label: "소룡동", medicalSpecialty: ["general"] },
    { id: "soryong", label: "개정동", medicalSpecialty: ["general"] },
    { id: "gaejeong", label: "수송동", medicalSpecialty: ["general"] },
    { id: "susong", label: "경장동", medicalSpecialty: ["general"] },
    { id: "gyeongjang", label: "조촌동", medicalSpecialty: ["general"] },
    { id: "jochon", label: "옥구읍", medicalSpecialty: ["general"] },
    { id: "okgu", label: "옥산면", medicalSpecialty: ["general"] },
    { id: "oksan", label: "회현면", medicalSpecialty: ["general"] },
    { id: "hoehyeon", label: "임피면", medicalSpecialty: ["general"] },
    { id: "impi", label: "서수면", medicalSpecialty: ["general"] },
    { id: "seosu", label: "대야면", medicalSpecialty: ["general"] },
    { id: "daeya", label: "개정면", medicalSpecialty: ["general"] },
    { id: "gaejeong", label: "성산면", medicalSpecialty: ["general"] },
    { id: "seongsan", label: "나포면", medicalSpecialty: ["general"] },
    { id: "napo", label: "옥서면", medicalSpecialty: ["general"] },
  ],

  // 전라북도 익산시의 동/읍/면
  "jeonbuk.iksan": [
    { id: "jungang", label: "중앙동", medicalSpecialty: ["general"] },
    { id: "yeong", label: "평화동", medicalSpecialty: ["general"] },
    { id: "pyeonghwa", label: "인화동", medicalSpecialty: ["general"] },
    { id: "inhwa", label: "마동", medicalSpecialty: ["general"] },
    { id: "ma", label: "남중동", medicalSpecialty: ["general"] },
    { id: "namjung", label: "모현동", medicalSpecialty: ["general"] },
    { id: "mohyeon", label: "송학동", medicalSpecialty: ["general"] },
    { id: "songhak", label: "영등동", medicalSpecialty: ["general"] },
    {
      id: "yeongdeung",
      label: "어양동",
      medicalSpecialty: ["general", "internal"],
    },
    { id: "eoyang", label: "신동", medicalSpecialty: ["general"] },
    { id: "sin", label: "팔봉동", medicalSpecialty: ["general"] },
    { id: "palbong", label: "삼성동", medicalSpecialty: ["general"] },
    { id: "samsung", label: "함열읍", medicalSpecialty: ["general"] },
    { id: "hamyeol", label: "오산면", medicalSpecialty: ["general"] },
    { id: "osan", label: "황등면", medicalSpecialty: ["general"] },
    { id: "hwangdeung", label: "함라면", medicalSpecialty: ["general"] },
    { id: "hamna", label: "웅포면", medicalSpecialty: ["general"] },
    { id: "ungpo", label: "성당면", medicalSpecialty: ["general"] },
    { id: "seongdang", label: "용안면", medicalSpecialty: ["general"] },
    { id: "yongan", label: "낭산면", medicalSpecialty: ["general"] },
    { id: "nangsan", label: "망성면", medicalSpecialty: ["general"] },
    { id: "mangseong", label: "여산면", medicalSpecialty: ["general"] },
    { id: "yeosan", label: "금마면", medicalSpecialty: ["general"] },
    { id: "geumma", label: "왕궁면", medicalSpecialty: ["general"] },
    { id: "wanggung", label: "춘포면", medicalSpecialty: ["general"] },
    { id: "chunpo", label: "삼기면", medicalSpecialty: ["general"] },
    { id: "samgi", label: "용동면", medicalSpecialty: ["general"] },
  ],

  // 전라북도 정읍시의 동/읍/면
  "jeonbuk.jeongeup": [
    { id: "suwon", label: "수성동", medicalSpecialty: ["general"] },
    { id: "suseong", label: "장명동", medicalSpecialty: ["general"] },
    { id: "jangmyeong", label: "내장상동", medicalSpecialty: ["general"] },
    {
      id: "naejangsang",
      label: "시기동",
      medicalSpecialty: ["general", "internal"],
    },
    { id: "sigi", label: "초산동", medicalSpecialty: ["general"] },
    { id: "chosan", label: "연지동", medicalSpecialty: ["general"] },
    { id: "yeonji", label: "농소동", medicalSpecialty: ["general"] },
    { id: "nongso", label: "상교동", medicalSpecialty: ["general"] },
    { id: "sanggyo", label: "정우면", medicalSpecialty: ["general"] },
    { id: "jeongu", label: "태인면", medicalSpecialty: ["general"] },
    { id: "taein", label: "감곡면", medicalSpecialty: ["general"] },
    { id: "gamgok", label: "옹동면", medicalSpecialty: ["general"] },
    { id: "ongdong", label: "칠보면", medicalSpecialty: ["general"] },
    { id: "chilbo", label: "산내면", medicalSpecialty: ["general"] },
    { id: "sannae", label: "산외면", medicalSpecialty: ["general"] },
    { id: "sanoe", label: "입암면", medicalSpecialty: ["general"] },
    { id: "ibam", label: "소성면", medicalSpecialty: ["general"] },
    { id: "soseong", label: "고부면", medicalSpecialty: ["general"] },
    { id: "gobu", label: "영원면", medicalSpecialty: ["general"] },
    { id: "yeongwon", label: "덕천면", medicalSpecialty: ["general"] },
    { id: "deokcheon", label: "이평면", medicalSpecialty: ["general"] },
    { id: "ipyeong", label: "정읍읍", medicalSpecialty: ["general"] },
    { id: "jeongupeup", label: "신태인읍", medicalSpecialty: ["general"] },
  ],

  // 전라북도 남원시의 동/읍/면
  "jeonbuk.namwon": [
    { id: "donggwang", label: "동충동", medicalSpecialty: ["general"] },
    { id: "dongchung", label: "죽항동", medicalSpecialty: ["general"] },
    {
      id: "jukhang",
      label: "노암동",
      medicalSpecialty: ["general", "internal"],
    },
    { id: "noam", label: "금동", medicalSpecialty: ["general"] },
    { id: "geum", label: "왕정동", medicalSpecialty: ["general"] },
    { id: "wangjeong", label: "향교동", medicalSpecialty: ["general"] },
    { id: "hyanggyo", label: "도통동", medicalSpecialty: ["general"] },
    { id: "dotong", label: "용정동", medicalSpecialty: ["general"] },
    { id: "yongjeong", label: "산곡동", medicalSpecialty: ["general"] },
    { id: "sangok", label: "조산동", medicalSpecialty: ["general"] },
    { id: "josan", label: "운봉읍", medicalSpecialty: ["general"] },
    { id: "unbong", label: "주천면", medicalSpecialty: ["general"] },
    { id: "jucheon", label: "수지면", medicalSpecialty: ["general"] },
    { id: "suji", label: "송동면", medicalSpecialty: ["general"] },
    { id: "songdong", label: "주생면", medicalSpecialty: ["general"] },
    { id: "jusaeng", label: "금지면", medicalSpecialty: ["general"] },
    { id: "geumji", label: "대강면", medicalSpecialty: ["general"] },
    { id: "daegang", label: "덕과면", medicalSpecialty: ["general"] },
    { id: "deokgwa", label: "보절면", medicalSpecialty: ["general"] },
    { id: "bojeol", label: "사매면", medicalSpecialty: ["general"] },
    { id: "samae", label: "산동면", medicalSpecialty: ["general"] },
    { id: "sandong", label: "이백면", medicalSpecialty: ["general"] },
    { id: "ibaek", label: "아영면", medicalSpecialty: ["general"] },
    { id: "ayeong", label: "인월면", medicalSpecialty: ["general"] },
    { id: "inwol", label: "옥정동", medicalSpecialty: ["general"] },
  ],

  // 전라북도 김제시의 동/읍/면
  "jeonbuk.gimje": [
    { id: "sinbong", label: "신풍동", medicalSpecialty: ["general"] },
    {
      id: "sinpung",
      label: "요촌동",
      medicalSpecialty: ["general", "internal"],
    },
    { id: "yochon", label: "검산동", medicalSpecialty: ["general"] },
    { id: "geomsan", label: "교월동", medicalSpecialty: ["general"] },
    { id: "gyowol", label: "만경읍", medicalSpecialty: ["general"] },
    { id: "mangyeong", label: "죽산면", medicalSpecialty: ["general"] },
    { id: "juksan", label: "백산면", medicalSpecialty: ["general"] },
    { id: "baeksan", label: "용지면", medicalSpecialty: ["general"] },
    { id: "yongji", label: "백구면", medicalSpecialty: ["general"] },
    { id: "baekgu", label: "부량면", medicalSpecialty: ["general"] },
    { id: "buyang", label: "공덕면", medicalSpecialty: ["general"] },
    { id: "gongdeok", label: "청하면", medicalSpecialty: ["general"] },
    { id: "cheongha", label: "성덕면", medicalSpecialty: ["general"] },
    { id: "seongdeok", label: "진봉면", medicalSpecialty: ["general"] },
    { id: "jinbong", label: "금구면", medicalSpecialty: ["general"] },
    { id: "geumgu", label: "봉남면", medicalSpecialty: ["general"] },
    { id: "bongnam", label: "황산면", medicalSpecialty: ["general"] },
    { id: "hwangsan", label: "금산면", medicalSpecialty: ["general"] },
    { id: "geumsan", label: "광활면", medicalSpecialty: ["general"] },
    { id: "gwanghwal", label: "진봉면", medicalSpecialty: ["general"] },
  ],

  // 전라북도 완주군의 읍/면
  "jeonbuk.wanju": [
    { id: "boan", label: "봉동읍", medicalSpecialty: ["general"] },
    { id: "bongdong", label: "삼례읍", medicalSpecialty: ["general"] },
    { id: "samrye", label: "이서면", medicalSpecialty: ["general"] },
    { id: "iseo", label: "소양면", medicalSpecialty: ["general"] },
    { id: "soyang", label: "구이면", medicalSpecialty: ["general"] },
    { id: "gui", label: "고산면", medicalSpecialty: ["general"] },
    { id: "gosan", label: "비봉면", medicalSpecialty: ["general"] },
    { id: "bibong", label: "운주면", medicalSpecialty: ["general"] },
    { id: "unju", label: "화산면", medicalSpecialty: ["general"] },
    { id: "hwasan", label: "동상면", medicalSpecialty: ["general"] },
    { id: "dongsang", label: "경천면", medicalSpecialty: ["general"] },
    { id: "gyeongcheon", label: "봉동읍", medicalSpecialty: ["general"] },
    { id: "bongdong", label: "용진읍", medicalSpecialty: ["general"] },
  ],
};
