/**
 * 전라남도 주요 시/군별 동/읍/면 정보
 */
export const jeonnamSubRegions = {
  // 전라남도 목포시의 동
  "jeonnam.mokpo": [
    { id: "sangdong", label: "상동", medicalSpecialty: ["general"] },
    {
      id: "hadong",
      label: "하당동",
      medicalSpecialty: ["general", "internal"],
    },
    { id: "yongdang", label: "용당동", medicalSpecialty: ["general"] },
    { id: "samhak", label: "삼학동", medicalSpecialty: ["general"] },
    { id: "donmyeong", label: "동명동", medicalSpecialty: ["general"] },
    { id: "songha", label: "호남동", medicalSpecialty: ["general"] },
    { id: "honam", label: "북항동", medicalSpecialty: ["general"] },
    { id: "bukhang", label: "용해동", medicalSpecialty: ["general"] },
    { id: "yonghae", label: "이로동", medicalSpecialty: ["general"] },
    { id: "iro", label: "옥암동", medicalSpecialty: ["general"] },
    { id: "ogam", label: "연산동", medicalSpecialty: ["general"] },
    { id: "yeonsan", label: "대양동", medicalSpecialty: ["general"] },
    { id: "daeyang", label: "연동", medicalSpecialty: ["general"] },
    { id: "yeondong", label: "삼향동", medicalSpecialty: ["general"] },
    { id: "samhyang", label: "원산동", medicalSpecialty: ["general"] },
    { id: "wonsan", label: "대성동", medicalSpecialty: ["general"] },
  ],

  // 전라남도 여수시의 동/읍/면
  "jeonnam.yeosu": [
    { id: "jungang", label: "중앙동", medicalSpecialty: ["general"] },
    { id: "donghong", label: "동려동", medicalSpecialty: ["general"] },
    { id: "dongnyeo", label: "신월동", medicalSpecialty: ["general"] },
    { id: "sinwol", label: "광림동", medicalSpecialty: ["general"] },
    { id: "gwangnim", label: "충무동", medicalSpecialty: ["general"] },
    { id: "chungmu", label: "여천동", medicalSpecialty: ["general"] },
    {
      id: "yeocheon",
      label: "여서동",
      medicalSpecialty: ["general", "internal"],
    },
    { id: "yeoseo", label: "시전동", medicalSpecialty: ["general"] },
    { id: "sijeon", label: "둔덕동", medicalSpecialty: ["general"] },
    { id: "dundeok", label: "만덕동", medicalSpecialty: ["general"] },
    { id: "mandeok", label: "쌍봉동", medicalSpecialty: ["general"] },
    { id: "ssangbong", label: "시전동", medicalSpecialty: ["general"] },
    { id: "sijeon", label: "여천동", medicalSpecialty: ["general"] },
    { id: "yeocheon", label: "소라면", medicalSpecialty: ["general"] },
    { id: "sora", label: "율촌면", medicalSpecialty: ["general"] },
    { id: "yulchon", label: "화양면", medicalSpecialty: ["general"] },
    { id: "hwayang", label: "남면", medicalSpecialty: ["general"] },
    { id: "nam", label: "화정면", medicalSpecialty: ["general"] },
    { id: "hwajeong", label: "삼산면", medicalSpecialty: ["general"] },
    { id: "samsan", label: "동문동", medicalSpecialty: ["general"] },
  ],

  // 전라남도 나주시의 동/읍/면
  "jeonnam.naju": [
    { id: "geumseo", label: "금남동", medicalSpecialty: ["general"] },
    { id: "geumnam", label: "성북동", medicalSpecialty: ["general"] },
    { id: "seongbuk", label: "영강동", medicalSpecialty: ["general"] },
    { id: "yeonggang", label: "이창동", medicalSpecialty: ["general"] },
    {
      id: "ichang",
      label: "빛가람동",
      medicalSpecialty: ["general", "internal"],
    },
    { id: "bitgaram", label: "송월동", medicalSpecialty: ["general"] },
    { id: "songwol", label: "영산동", medicalSpecialty: ["general"] },
    { id: "yeongsan", label: "남평읍", medicalSpecialty: ["general"] },
    { id: "nampyeong", label: "산포면", medicalSpecialty: ["general"] },
    { id: "sanpo", label: "다시면", medicalSpecialty: ["general"] },
    { id: "dasi", label: "문평면", medicalSpecialty: ["general"] },
    { id: "munpyeong", label: "노안면", medicalSpecialty: ["general"] },
    { id: "noan", label: "금천면", medicalSpecialty: ["general"] },
    { id: "geumcheon", label: "산포면", medicalSpecialty: ["general"] },
    { id: "sanpo", label: "다도면", medicalSpecialty: ["general"] },
    { id: "dado", label: "봉황면", medicalSpecialty: ["general"] },
    { id: "bonghwang", label: "공산면", medicalSpecialty: ["general"] },
    { id: "gongsan", label: "왕곡면", medicalSpecialty: ["general"] },
    { id: "wanggok", label: "반남면", medicalSpecialty: ["general"] },
    { id: "bannam", label: "동강면", medicalSpecialty: ["general"] },
    { id: "donggang", label: "다시면", medicalSpecialty: ["general"] },
  ],

  // 전라남도 광양시의 동/읍/면
  "jeonnam.gwangyang": [
    {
      id: "jungang",
      label: "중마동",
      medicalSpecialty: ["general", "internal"],
    },
    { id: "jungma", label: "광영동", medicalSpecialty: ["general"] },
    { id: "gwangyeong", label: "금호동", medicalSpecialty: ["general"] },
    { id: "geumho", label: "태인동", medicalSpecialty: ["general"] },
    { id: "taein", label: "골약동", medicalSpecialty: ["general"] },
    { id: "golyak", label: "광양읍", medicalSpecialty: ["general"] },
    { id: "gwangyangeup", label: "봉강면", medicalSpecialty: ["general"] },
    { id: "bonggang", label: "옥룡면", medicalSpecialty: ["general"] },
    { id: "okryong", label: "옥곡면", medicalSpecialty: ["general"] },
    { id: "okgok", label: "진상면", medicalSpecialty: ["general"] },
    { id: "jinsang", label: "진월면", medicalSpecialty: ["general"] },
    { id: "jinwol", label: "다압면", medicalSpecialty: ["general"] },
  ],

  // 전라남도 담양군의 읍/면
  "jeonnam.damyang": [
    { id: "damyang", label: "담양읍", medicalSpecialty: ["general"] },
    { id: "gosan", label: "고서면", medicalSpecialty: ["general"] },
    { id: "goseo", label: "남면", medicalSpecialty: ["general"] },
    { id: "nam", label: "창평면", medicalSpecialty: ["general"] },
    { id: "changpyeong", label: "대덕면", medicalSpecialty: ["general"] },
    { id: "daedeok", label: "무정면", medicalSpecialty: ["general"] },
    { id: "mujeong", label: "금성면", medicalSpecialty: ["general"] },
    { id: "geumseong", label: "용면", medicalSpecialty: ["general"] },
    { id: "yong", label: "월산면", medicalSpecialty: ["general"] },
    { id: "wolsan", label: "수북면", medicalSpecialty: ["general"] },
    { id: "subuk", label: "대전면", medicalSpecialty: ["general"] },
    { id: "daejeon", label: "봉산면", medicalSpecialty: ["general"] },
  ],

  // 전라남도 곡성군의 읍/면
  "jeonnam.gokseong": [
    { id: "gokseong", label: "곡성읍", medicalSpecialty: ["general"] },
    { id: "ok", label: "오곡면", medicalSpecialty: ["general"] },
    { id: "ogok", label: "삼기면", medicalSpecialty: ["general"] },
    { id: "samgi", label: "석곡면", medicalSpecialty: ["general"] },
    { id: "seokgok", label: "목사동면", medicalSpecialty: ["general"] },
    { id: "moksadong", label: "죽곡면", medicalSpecialty: ["general"] },
    { id: "jukgok", label: "고달면", medicalSpecialty: ["general"] },
    { id: "godal", label: "옥과면", medicalSpecialty: ["general"] },
    { id: "okgwa", label: "입면", medicalSpecialty: ["general"] },
    { id: "ib", label: "겸면", medicalSpecialty: ["general"] },
    { id: "gyeom", label: "오산면", medicalSpecialty: ["general"] },
  ],

  // 전라남도 구례군의 읍/면
  "jeonnam.gurye": [
    { id: "gurye", label: "구례읍", medicalSpecialty: ["general"] },
    { id: "muncheok", label: "문척면", medicalSpecialty: ["general"] },
    { id: "toji", label: "토지면", medicalSpecialty: ["general"] },
    { id: "masu", label: "마산면", medicalSpecialty: ["general"] },
    { id: "gungdo", label: "광의면", medicalSpecialty: ["general"] },
    { id: "gwangui", label: "용방면", medicalSpecialty: ["general"] },
    { id: "yongbang", label: "산동면", medicalSpecialty: ["general"] },
    { id: "sandong", label: "신동면", medicalSpecialty: ["general"] },
  ],

  // 전라남도 고흥군의 읍/면
  "jeonnam.goheung": [
    { id: "goheung", label: "고흥읍", medicalSpecialty: ["general"] },
    { id: "donghyang", label: "도양읍", medicalSpecialty: ["general"] },
    { id: "doyang", label: "풍양면", medicalSpecialty: ["general"] },
    { id: "pungyang", label: "도덕면", medicalSpecialty: ["general"] },
    { id: "dodeok", label: "금산면", medicalSpecialty: ["general"] },
    { id: "geumsan", label: "도화면", medicalSpecialty: ["general"] },
    { id: "dohwa", label: "포두면", medicalSpecialty: ["general"] },
    { id: "podu", label: "봉래면", medicalSpecialty: ["general"] },
    { id: "bongrae", label: "동일면", medicalSpecialty: ["general"] },
    { id: "dongil", label: "점암면", medicalSpecialty: ["general"] },
    { id: "jeomam", label: "영남면", medicalSpecialty: ["general"] },
    { id: "yeongnam", label: "과역면", medicalSpecialty: ["general"] },
    { id: "gwayeok", label: "남양면", medicalSpecialty: ["general"] },
    { id: "namyang", label: "두원면", medicalSpecialty: ["general"] },
    { id: "duwon", label: "영도면", medicalSpecialty: ["general"] },
  ],

  // 전라남도 보성군의 읍/면
  "jeonnam.boseong": [
    { id: "boseong", label: "보성읍", medicalSpecialty: ["general"] },
    { id: "beolgyo", label: "벌교읍", medicalSpecialty: ["general"] },
    { id: "nodong", label: "노동면", medicalSpecialty: ["general"] },
    { id: "miryeok", label: "미력면", medicalSpecialty: ["general"] },
    { id: "ungchi", label: "웅치면", medicalSpecialty: ["general"] },
    { id: "deungnyang", label: "득량면", medicalSpecialty: ["general"] },
    { id: "hoewon", label: "회천면", medicalSpecialty: ["general"] },
    { id: "hoecheon", label: "율어면", medicalSpecialty: ["general"] },
    { id: "yureo", label: "복내면", medicalSpecialty: ["general"] },
    { id: "bongnae", label: "문덕면", medicalSpecialty: ["general"] },
    { id: "mundeok", label: "조성면", medicalSpecialty: ["general"] },
    { id: "joseong", label: "겸백면", medicalSpecialty: ["general"] },
  ],

  // 전라남도 화순군의 읍/면
  "jeonnam.hwasun": [
    { id: "hwasun", label: "화순읍", medicalSpecialty: ["general"] },
    { id: "hancheon", label: "한천면", medicalSpecialty: ["general"] },
    { id: "chunyang", label: "춘양면", medicalSpecialty: ["general"] },
    { id: "cheongryong", label: "청풍면", medicalSpecialty: ["general"] },
    { id: "cheongpung", label: "이양면", medicalSpecialty: ["general"] },
    { id: "iyang", label: "능주면", medicalSpecialty: ["general"] },
    { id: "neungju", label: "도곡면", medicalSpecialty: ["general"] },
    { id: "dogok", label: "도암면", medicalSpecialty: ["general"] },
    { id: "doam", label: "이서면", medicalSpecialty: ["general"] },
    { id: "iseo", label: "북면", medicalSpecialty: ["general"] },
    { id: "buk", label: "동복면", medicalSpecialty: ["general"] },
    { id: "dongbok", label: "남면", medicalSpecialty: ["general"] },
    { id: "nam", label: "동면", medicalSpecialty: ["general"] },
  ],
};
